Added search functionality.
iamstevendao/vue-tel-input pull request #305
Opened 2021-11-26 16:58 UTC by kashaudhan

Search functionality can be disabled by by isSearchable flag. By default it is set to true.

2021-11-29 03:36 UTC, iamstevendao requested changes

2021-11-29 03:36 UTC, iamstevendao commented on src/components/vue-tel-input.vue
> +    isSearchable: {
Can you use the `getDefault()` instead of a hard-coded value?

2021-11-29 16:50 UTC, kashaudhan commented
fixed default for isSearchable flag

2021-12-02 13:54 UTC, merged

2021-12-02 14:22 UTC, iamstevendao commented
@kashaudhan thanks for your help! i added a minor clean up for consistency: 5c044d4c840cdafe35096a4082ba1499ff7be52a. it's available in v5.7.0